MANTARGET= \
	ccs_config_dump.8 \
	ccs_config_validate.8 \
	ccs_tool.8 \
	confdb2ldif.8

include ../../../make/defines.mk
include $(OBJDIR)/make/install.mk
include $(OBJDIR)/make/uninstall.mk

all:

clean:
