MANTARGET= \
	gfs.8 \
	mount.gfs.8 \
	gfs_edit.8 \
	fsck.gfs.8 \
	gfs_grow.8 \
	gfs_jadd.8 \
	mkfs.gfs.8 \
	gfs_quota.8 \
	gfs_tool.8

include ../../make/defines.mk
include $(OBJDIR)/make/install.mk
include $(OBJDIR)/make/uninstall.mk

all:

clean:
