MANTARGET= \
	clubufflush.8 \
	clufindhostname.8 \
	clulog.8 \
	rgmanager.8 \
	clurgmgrd.8 \
	clustat.8 \
	clusvcadm.8

include ../../make/defines.mk
include $(OBJDIR)/make/install.mk
include $(OBJDIR)/make/uninstall.mk

all:

clean:

check:
