.TH GROUP_TOOL 8 2009-01-19 cluster cluster

.SH NAME
group_tool \- run common fence_tool, dlm_tool, gfs_control commands

.SH SYNOPSIS
.B group_tool
[COMMAND] [OPTIONS]

.SH DESCRIPTION
This utility is deprecated and the new replacements are shown.  See
.BR fence_tool (8),
.BR dlm_tool (8),
.BR gfs_control (8)
man pages for more information about the new commands.

.TP
.B ls
runs
.BR "fence_tool ls " ;
.BR "dlm_tool ls " ;
.B gfs_control ls
.TP
.B dump fence
equivalent to new
.B fence_tool dump
.TP
.B dump dlm
equivalent to new
.B dlm_tool dump
.TP
.B dump gfs
equivalent to new
.B gfs_control dump
.TP
.BI "dump plocks" " name"
equivalent to new
.BI "dlm_tool plocks" " name"

.SS Cluster Uprading

When performing a rolling upgrade from cluster2 to cluster3, the
.BR groupd (8)
daemon will be running and group_tool can be used with groupd like it was in
cluster2.

.TP
.B ls \-g1
queries and displays the internal groupd state.
.TP
.B dump
queries and dumps the groupd debug buffer.
.TP
.B compat
queries and displays the internal groupd compatibility mode.

.SH OPTIONS
.TP
.BI \-g " num"
Force old groupd queries with 1.
.TP 
.B \-n
Show all node information in ls.
.TP 
.B \-v
Show verbose information from groupd with ls \-g1.
.TP
.B \-h
Print a help message describing available options, then exit.
.TP
.B \-V
Print program version information, then exit.

.SH SEE ALSO
.BR cman (5),
.BR groupd (8),
.BR fence_tool (8),
.BR dlm_tool (8),
.BR gfs_control(8)

