.TH GROUPD 8 2009-01-19 cluster cluster

.SH NAME
groupd \- compatibility daemon for fenced, dlm_controld and gfs_controld

.SH SYNOPSIS
.B groupd
[OPTIONS]

.SH DESCRIPTION

The groupd daemon and libgroup library are used by the fenced,
dlm_controld and gfs_controld daemons when they are operating in
cluster2-compatible mode to perform a rolling cluster upgrade from
cluster2 to cluster3.

See
.BR cman (5)
for more information on the
.B upgrading
configuration option needed to perform a rolling upgrade.

When the upgrading option is enabled, cman adds the following to the
online configuration:

	<group groupd_compat="1"/>

This setting causes the cman init script to start the groupd daemon,
and causes the groupd, fenced, dlm_controld and gfs_controld daemons to
operate in the old cluster2 mode so they will be compatible with cluster2
nodes in the cluster that have not yet been upgraded.

The upgrading setting, including the groupd_compat setting,
.B cannot be changed in a running cluster.
The entire cluster must be taken offline to change these because the new
cluster3 default modes are not compatible with the old cluster2 modes.
The upgrading/compat settings cause the new cluster3 daemons to run the
old cluster2 code and protocols.

.SH OPTIONS
Command line options override a corresponding setting in cluster.conf.

.TP
.B \-D
Enable debugging to stderr and don't fork.
.TP
.B \-L
Enable debugging to log file.
.TP
.BI \-g " num"
groupd compatibility mode, 0 off, 1 on. Default 0.
.TP
.B \-h
Print a help message describing available options, then exit.
.TP
.B \-V
Print program version information, then exit.

.SH SEE ALSO
.BR cman (5),
.BR fenced (8),
.BR dlm_controld (8),
.BR gfs_controld (8)

