MANTARGET= \
	dlm_controld.8 \
	gfs_controld.8 \
	gfs_control.8 \
	group_tool.8 \
	groupd.8

include ../../make/defines.mk
include $(OBJDIR)/make/install.mk
include $(OBJDIR)/make/uninstall.mk

all:

clean:
